let randomString = `cypress${Math.floor(10000 + Math.random() * 90000)}`;

export default {
  textureText: "texture-text",
  fontSize: "texture-font_size",
  validEmail: "atchyutha.padarthi@hcrobo.com",
  inValidEmail: "admini@hcrobo.com",
  testDesignEngineerEmail: "testdesignengineer@hcrobo.com",
  password: "Cnsw-123",
  notExistingEmail: "1@1.1",
  invalidPwd: "adm",
  sqlInjection: "SELECT * FROM Users WHERE UserId = 105 OR 1=1",
  emptyString: "",
  horizontalMeasurement:
    "#canvas3DContainer > div.relative.static.width-100vw.height-100vh.SideToolsBarContainer > div > div > div:nth-child(4) > div > div > svg",
  verticalMeasurement:
    "#canvas3DContainer > div.relative.static.width-100vw.height-100vh.SideToolsBarContainer > div > div > div:nth-child(3) > div > div > svg",
  pointToPointMeasurement:
    "#canvas3DContainer > div.relative.static.width-100vw.height-100vh.SideToolsBarContainer > div > div > div:nth-child(2) > div > div > svg",
  angleMeasurement:
    "#canvas3DContainer > div.relative.static.width-100vw.height-100vh.SideToolsBarContainer > div > div > div:nth-child(5) > div > div > svg",
  testEmail1: "admin@hcrobo.com",
  testEmail: `${randomString}@cypresstest.com`,
  testPassword: "admin-123",
  testConfirmPassword: "admin123",
  testUserName: randomString,
  pwdMismatchString: "Doesn't match with password ",
  userExistsString: "Already registered username ",
  emailExistingString: "Already registered email ",
  adminUserEmail: "admin@hcrobo.com",
  emailEmptyString: "Invalid email format. ",
  adminUserName: "Admin",
  caseSensitiveAdminEmail: "Admin@hcrobo.com",

  testuserEmail: "abc@hcrobo.com",
  testuserPwd: "cnsw-123",
  produserEmail: "admin@hcrobo.com",
  ProduserPwd: "Cnsw-123",
  // ! Poles Input fields Test data
  Integers: "123",
  zero: "0",
  negative: "-1-2-3-4-5-6-7-8-9",
  MoreThanFiveValues: "49999", // For circumference and quantity data fields only
  FloatingPoints: "0.75 ",
  ScientificNotation: "123e2, 134e2",
  StringData: "jhsgdfjksdghfskd kasgfksjfdghfjkdghfdjghsfdjkg skfdgjhskjfgh",
  Alphanumeric: "12abcd",
  SpacesOnly: "    /t ",
  Scripts: "<script>alert('XSS')</script> ",
  quotes: "\"Test\" 'Data'",
  specialchars: "~!@#$%^&*()_+{}|:?><,./;'[]=-`",
  GeoData: " Latitude: 37.7749, Longitude: -122.4194 ",
  GeoDataOriginpoint: "Latitude: 0, Longitude: 0",
  ClientEmail: "atchyutha.padarthi@hcrobo.com",
  AdminEmail: "admin@hcrobo.com",
  ClientPassword: "Cnsw-123",
  AdminPassword: "Cnsw-123",
  SpecialCharEmail: "adminh%crobo.com",
  Case_Insensitive_Email: "Admin@hcrobo.com",
  lowerCaseEmail: "admin@hcrobo.com",
  upperCaseEmail: "ADMIN@HCROBO.COM",
  MixedCaseEmail: "Admin@hCrobo.com",
  notExistingEmail: "1@1.1",
  invalidFormatEmail: "atchyutha.padarthi@hcroboco",
  nonExistingEmailForgot: "notExisting@hcrobo.com",
  validForgotEmail: "atchyutha.padarthi@hcrobo.com",
  resetPasswordEmail:"loadtester2@hcr.com",
};
